'use strict';
const $=id=>document.getElementById(id), el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==null)n.textContent=text;Object.assign(n,attrs);return n;};
let currentAbort=null, runToken=0;
let worker=null, nextId=0, pending=new Map(), activeModel=null, busy=false, jobs=[], currentUrls=[], builtins=[];
const files={history:[],weather:[],truth:[],plan:[],observed:[]};
const names={date:'날짜',target:'수요 / 계획량',temp_avg:'평균기온',temp_max:'최고기온',temp_min:'최저기온'};
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function startWorker(){worker=new Worker('./worker.js');worker.onmessage=({data})=>{if(data.progress){status(data.progress);return;}const task=pending.get(data.id);if(!task)return;pending.delete(data.id);if(data.fatal){worker.terminate();worker=null;}data.error?task.reject(Error(data.error)):task.resolve(data.result);};worker.onerror=e=>{worker?.terminate();worker=null;activeModel=null;for(const role of Object.keys(files)){files[role]=[];$('items-'+role).replaceChildren();}status('실행 환경을 불러오지 못했습니다. 인터넷 연결을 확인하고 모델과 입력 파일을 다시 불러오세요.',true);for(const t of pending.values())t.reject(Error(e.message));pending.clear();};}
function request(action,payload){if(!worker)startWorker();return new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});worker.postMessage({id,action,payload});});}
async function task(fn){if(busy)return;busy=true;runToken++;currentAbort=new AbortController();$('controls').disabled=true;$('cancel').hidden=false;try{await fn();}catch(e){status(e.message,true);}finally{busy=false;$('controls').disabled=false;$('cancel').hidden=true;$('run').disabled=!activeModel;}}
$('cancel').onclick=()=>{runToken++;currentAbort?.abort();worker?.terminate();worker=null;for(const t of pending.values())t.reject(Error('작업이 중지되었습니다. 모델과 입력 파일을 다시 불러오세요.'));pending.clear();activeModel=null;$('model-info').textContent='실행 환경이 초기화되었습니다.';for(const role of Object.keys(files)){files[role]=[];$('items-'+role).replaceChildren();}status('작업이 중지되었습니다. 모델과 입력 파일을 다시 불러오세요.');};
function applyTheme(dark){
 document.body.classList.toggle('dark',dark);
 $('theme').textContent=dark?'라이트 모드':'다크 모드';
 $('theme').setAttribute('aria-label',dark?'라이트 모드로 변경':'다크 모드로 변경');
 document.querySelector('meta[name="theme-color"]').content=dark?'#111318':'#ffffff';
}
$('theme').onclick=()=>{const dark=!document.body.classList.contains('dark');applyTheme(dark);try{localStorage.setItem('forecast-theme',dark?'dark':'light');}catch{}};
let savedTheme='light';try{savedTheme=localStorage.getItem('forecast-theme')||'light';}catch{}
applyTheme(savedTheme==='dark');
async function upload(file,inspect=false){const token=runToken;if(file.size>100*1024*1024)throw Error('개별 파일은 100MB 이하로 준비하세요.');const bytes=await file.arrayBuffer();if(token!==runToken)throw Error('작업이 중지되었습니다.');return request('upload',{id:String(++nextId),name:file.name,bytes,inspect});}
function setModel(meta){activeModel=meta;const target=meta.target==='normal'?'일반 사입량':'열병합 포함 사입량';$('model-info').textContent=`${meta.display_name||target}\n${target} · ${meta.tree_count.toLocaleString()}개 트리\n모델 기준일 ${meta.trained_through}\n과거 ${meta.config.window_size}일 · ${meta.config.horizon}일씩 예측`;
 const start=new Date(meta.trained_through+'T00:00:00Z');start.setUTCDate(start.getUTCDate()+1);const end=new Date(start);end.setUTCDate(end.getUTCDate()+30);$('start').value=start.toISOString().slice(0,10);$('end').value=end.toISOString().slice(0,10);status('모델을 불러왔습니다. 기간과 입력 파일을 확인한 뒤 예측을 시작하세요.');}
$('load-model').onclick=()=>task(async()=>{const selected=[...$('model-files').files];if(!selected.length)throw Error('모델 ZIP 또는 필수 파일 3개를 선택하세요.');activeModel=null;$('model-info').textContent='모델을 불러오는 중입니다.';const paths=[];for(const file of selected)paths.push((await upload(file)).path);setModel(await request('model',paths));});
$('load-builtin').onclick=()=>task(async()=>{const entry=builtins[Number($('builtin').value)];if(!entry)throw Error('등록 모델을 선택하세요.');activeModel=null;$('model-info').textContent='등록 모델을 불러오는 중입니다.';const paths=[];
 for(const name of ['config.json','model.json','climate_history.csv']){const response=await fetch('./storage/models/'+entry.directory+'/'+name,{signal:currentAbort.signal});if(!response.ok)throw Error('등록 모델 파일이 없습니다: '+name);paths.push((await upload(new File([await response.arrayBuffer()],name))).path);}const meta=await request('model',paths);meta.display_name=entry.name;meta.model_directory=entry.directory;setModel(meta);});
async function manifest(){try{const res=await fetch('./storage/models/manifest.json');if(!res.ok)throw Error('모델 목록을 읽을 수 없습니다.');builtins=await res.json();if(!Array.isArray(builtins)||builtins.some(x=>!x.name||!/^[a-zA-Z0-9_-]+$/.test(x.directory)))throw Error('등록 모델 목록 형식이 잘못되었습니다.');$('builtin').replaceChildren(...(builtins.length?builtins.map((x,i)=>el('option',x.name,{value:String(i)})):[el('option','등록 모델 없음 · 내 모델을 불러오세요',{value:''})]));$('load-builtin').disabled=!builtins.length;}catch(e){$('builtin').replaceChildren(el('option','모델 목록 없음'));status(e.message+' 내 모델 파일은 사용할 수 있습니다.',true);}}
const roles=[['history','과거 수요 이력','선택하지 않으면 모델에 포함된 이력을 사용합니다.'],['weather','예측 입력 기온','평균기온 또는 최고·최저 쌍을 지정하세요.'],['truth','비교용 GT','GT 비교를 켜면 적용합니다. 미첨부 시 이력의 수요를 비교합니다.'],['plan','비교용 사업 계획','계획량은 그래프에만 표시합니다.'],['observed','비교용 실측 기온','예측 입력에 사용하지 않고 결과에만 표시합니다.']];
for(const [role,title,hint]of roles){const detail=el('details',null),summary=el('summary',title+' · CSV / XLSX');detail.append(summary,el('p',hint,{className:'helper'}));const label=el('label','파일 선택'),input=el('input',null,{type:'file',accept:'.csv,.xlsx',multiple:true});label.append(input);const host=el('div',null,{id:'items-'+role});detail.append(label,host);$('file-inputs').append(detail);
 input.onchange=()=>task(async()=>{for(const file of input.files){if(!/\.(csv|xlsx)$/i.test(file.name))throw Error('CSV 또는 XLSX 파일을 선택하세요.');status(file.name+' 파일을 분석합니다.');const result=await upload(file,true), item={path:result.path,name:file.name,mapping:{},start:'',end:''};const card=el('div',null,{className:'file-item'});card.append(el('strong',file.name+' · '+result.rows.toLocaleString()+'행'));const grid=el('div',null,{className:'grid'});
 const keys=role==='truth'||role==='plan'?['date','target']:role==='history'?Object.keys(names):['date','temp_avg','temp_max','temp_min'];
 for(const key of keys){const l=el('label',names[key]),select=el('select',null);select.append(el('option','지정 안 함',{value:''}),...result.columns.map(c=>el('option',c,{value:c})));select.value=result.mapping[key]||'';item.mapping[key]=select.value;select.onchange=()=>{item.mapping[key]=select.value;};l.append(select);grid.append(l);}
 for(const [key,caption]of [['start','적용 시작일 · 선택'],['end','적용 종료일 · 선택']]){const l=el('label',caption),date=el('input',null,{type:'date'});date.onchange=()=>{item[key]=date.value;};l.append(date);grid.append(l);}card.append(grid);const remove=el('button','파일 제외',{type:'button'});remove.onclick=()=>{files[role]=files[role].filter(x=>x!==item);card.remove();};card.append(remove);host.append(card);files[role].push(item);if(role==='truth')$('gt').checked=true;}
 input.value='';status('입력 파일 분석이 완료되었습니다. 컬럼과 적용 기간을 확인하세요.');});}
$('add-range').onclick=()=>{const row=el('div',null,{className:'grid climate-range'});for(const label of ['시작일','종료일']){const l=el('label',label),input=el('input',null,{type:'date',required:true});l.append(input);row.append(l);}const remove=el('button','구간 제외',{type:'button'});remove.onclick=()=>row.remove();row.append(remove);$('ranges').append(row);};
$('forecast-form').onsubmit=e=>{e.preventDefault();task(async()=>{if(!activeModel)throw Error('모델을 먼저 불러오세요.');const p={start:$('start').value,end:$('end').value,years:Number($('years').value),mc:Number($('mc').value),delta:Number($('delta').value),minus:Number($('minus').value),plus:Number($('plus').value),limit_history:$('limit-history').checked,use_stored_weather:$('use-stored-weather').checked,climate_all:$('climate-all').checked,gt:$('gt').checked,files,climate_ranges:[...document.querySelectorAll('.climate-range')].map(row=>({start:row.querySelectorAll('input')[0].value,end:row.querySelectorAll('input')[1].value}))};if(p.start>p.end)throw Error('종료일은 시작일 이후여야 합니다.');const result=await request('predict',p);result.metadata.model_name=activeModel.display_name||activeModel.target;result.metadata.model_directory=activeModel.model_directory||null;jobs.push(result);$('job-list').replaceChildren(...jobs.map((j,i)=>el('option',`${i+1}. ${j.metadata.model_name} · ${j.metadata.start} ~ ${j.metadata.end}`,{value:String(i)})));$('job-list').value=String(jobs.length-1);showResult(result);status('예측이 완료되었습니다. 결과와 적용 기온을 확인하세요.');});};
function downloadButton(label,name,content,type){const url=URL.createObjectURL(new Blob([type==='text/csv'?'\ufeff':'',content],{type:type+';charset=utf-8'}));currentUrls.push(url);return el('a',label,{href:url,download:name,className:'download-link'});}
function showResult(result){$('empty').hidden=true;$('output').hidden=false;for(const url of currentUrls)URL.revokeObjectURL(url);currentUrls=[];const rows=result.records,total=rows.reduce((s,r)=>s+r.prediction,0),peak=Math.max(...rows.map(r=>r.prediction));const summary=[['기간 예측 합계',Math.round(total).toLocaleString('ko-KR')],['최대 일별 예측',Math.round(peak).toLocaleString('ko-KR')],['GT WAPE',result.metrics?.prediction?.WAPE!=null?result.metrics.prediction.WAPE.toFixed(2)+'%':'비교 없음']];$('summary').replaceChildren(...summary.map(([a,b])=>{const d=el('div',null);d.append(el('small',a),el('strong',b));return d;}));const m=result.metadata;$('result-caption').textContent=`${m.model_name||m.target} · ${m.start} ~ ${m.end} · 예측 기준일 ${m.origin} · N개년 보완 ${m.scenarios.fallback_days}일(공백 포함) · MC ${m.scenarios.mc_runs}회 · 단위는 입력 수요와 동일`;$('chart').replaceChildren();window.ForecastChart($('chart'),rows);$('metadata').textContent=JSON.stringify({metadata:m,metrics:result.metrics},null,2);$('downloads').replaceChildren(downloadButton('일별 CSV','prediction.csv',result.csv,'text/csv'),downloadButton('월별 시나리오 CSV','prediction.monthly.csv',result.monthly_csv,'text/csv'),downloadButton('설정·평가 JSON','prediction.metadata.json',JSON.stringify({metadata:m,metrics:result.metrics},null,2),'application/json'));if(result.bridge_csv.trim())$('downloads').append(downloadButton('공백 보완 CSV','prediction.bridge.csv',result.bridge_csv,'text/csv'));}
$('job-list').onchange=()=>{const result=jobs[Number($('job-list').value)];if(result)showResult(result);};
manifest();
